import express from "express";import {Pool} from "pg";import {createClient} from "redis";import crypto from "node:crypto";
const app=express();app.use(express.json({limit:"10mb"}));const pool=new Pool({connectionString:process.env.DATABASE_URL});const port=Number(process.env.PORT??3405);const redisUrl=process.env.REDIS_URL??"redis://redis:6379";const redis=createClient({url:redisUrl}); redis.on("error",()=>undefined); void redis.connect().catch(()=>undefined); async function enqueue(payload:unknown){if(redis.isOpen) await redis.lPush("q:ocr-processing",JSON.stringify(payload));}
const s="ocr_domain";
app.get("/health/live",(_,r)=>r.json({status:"ok",service:"service-ocr"}));app.get("/health/ready",async(_,r)=>{try{await pool.query("select 1");r.json({status:"ok"})}catch{r.status(503).json({status:"not_ready"})}});
app.post("/api/v1/ocr-jobs",async(req,res)=>{const b=req.body??{};const id=crypto.randomUUID();const idem=req.header("x-idempotency-key")??id;const c=await pool.connect();try{await c.query("begin");const old=await c.query(`select * from ${s}.jobs where idempotency_key=$1`,[idem]);if(old.rowCount){await c.query("rollback");return res.status(200).json({data:old.rows[0]})}const q=await c.query(`insert into ${s}.jobs(id,family_id,uploaded_by,store_id,object_key,mime_type,status,idempotency_key) values($1,$2,$3,$4,$5,$6,'PROCESSING',$7) returning *`,[id,b.familyId,b.userId,b.storeId??null,b.objectKey??`receipts/${id}`,b.mimeType??"image/jpeg",idem]);await c.query("commit");await enqueue({eventId:id,eventType:"RECEIPT_OCR_REQUESTED",timestamp:new Date().toISOString(),data:{jobId:id,familyId:b.familyId,userId:b.userId,objectKey:b.objectKey}});res.status(202).json({data:{jobId:id,status:"PROCESSING",estimatedTimeSeconds:3}})}catch(e){await c.query("rollback");res.status(400).json({error:{code:"OCR_JOB_CREATE_FAILED",message:String(e)}})}finally{c.release()}});
app.get("/api/v1/ocr-jobs",async(req,res)=>{const familyId=String(req.query.familyId??"");const status=String(req.query.status??"");const q=await pool.query(`select id,family_id,uploaded_by,store_id,object_key,status,created_at,updated_at from ${s}.jobs where family_id=$1 and ($2='' or status=$2) order by created_at desc limit 100`,[familyId,status]);res.json({data:{jobs:q.rows}})});
app.get("/api/v1/ocr-jobs/:id",async(req,res)=>{const q=await pool.query(`select * from ${s}.jobs where id=$1`,[req.params.id]);if(!q.rowCount)return res.status(404).json({error:{code:"NOT_FOUND"}});res.json({data:q.rows[0]})});
app.get("/api/v1/ocr-jobs/:id/drafts",async(req,res)=>{const q=await pool.query(`select j.*,coalesce(json_agg(d order by d.created_at) filter(where d.id is not null),'[]') drafts from ${s}.jobs j left join ${s}.drafts d on d.job_id=j.id where j.id=$1 group by j.id`,[req.params.id]);if(!q.rowCount)return res.status(404).json({error:{code:"NOT_FOUND"}});res.json({data:q.rows[0]})});
app.post("/api/v1/ocr-jobs/:id/confirm",async(req,res)=>{const c=await pool.connect();try{await c.query("begin");const j=await c.query(`select * from ${s}.jobs where id=$1 for update`,[req.params.id]);if(!j.rowCount){await c.query("rollback");return res.status(404).json({error:{code:"NOT_FOUND"}})}await c.query(`update ${s}.jobs set status='CONFIRMED',confirmed_at=now(),confirmation_payload=$2 where id=$1`,[req.params.id,JSON.stringify(req.body??{})]);await c.query("commit");res.status(202).json({data:{accepted:true,jobId:req.params.id}})}catch(e){await c.query("rollback");res.status(400).json({error:{code:"CONFIRM_FAILED",message:String(e)}})}finally{c.release()}});
app.post("/api/v1/ocr/barcode-extract",async(req,res)=>{res.status(202).json({data:{accepted:true,jobId:crypto.randomUUID(),barcode:null,status:"PROCESSING"}})});
async function ensureSchema(){await pool.query(`create schema if not exists ${s}`);await pool.query(`create table if not exists ${s}.jobs(id uuid primary key,family_id text,uploaded_by text,store_id text,object_key text,mime_type text,status text not null,idempotency_key text unique,confirmed_at timestamptz,confirmation_payload jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now())`);await pool.query(`create table if not exists ${s}.drafts(id uuid primary key default gen_random_uuid(),job_id uuid not null references ${s}.jobs(id) on delete cascade,payload jsonb,created_at timestamptz not null default now())`);}
await ensureSchema();
app.listen(port,"0.0.0.0",()=>console.log(JSON.stringify({service:"service-ocr",port})));
