import {createServer} from "node:http"; import {randomUUID} from "node:crypto";
const port=Number(process.env.PORT??3012),service=process.env.SERVICE_NAME??"families"; let requests=0,errors=0,totalMs=0,inFlight=0;
const log=(level:string,event:string,fields:Record<string,unknown>={})=>console.log(JSON.stringify({ts:new Date().toISOString(),level,service,event,...fields}));
const send=(res:import("node:http").ServerResponse,status:number,body:unknown,id:string)=>{res.statusCode=status;res.setHeader("content-type","application/json");res.setHeader("x-request-id",id);res.end(JSON.stringify(body));};
createServer((req,res)=>{const started=process.hrtime.bigint(),id=String(req.headers["x-request-id"]??randomUUID()),trace=String(req.headers.traceparent??"");inFlight++;res.setHeader("x-request-id",id);if(trace)res.setHeader("traceparent",trace);
try{if(req.url==="/metrics"){res.statusCode=200;res.setHeader("content-type","text/plain; version=0.0.4");res.end(`# TYPE http_requests_total counter\nhttp_requests_total ${requests}\n# TYPE http_errors_total counter\nhttp_errors_total ${errors}\n# TYPE http_requests_in_flight gauge\nhttp_requests_in_flight ${inFlight}\n# TYPE http_request_duration_ms_sum counter\nhttp_request_duration_ms_sum ${totalMs}\n`);return;}
if(req.url==="/health/live"){send(res,200,{status:"ok",service},id);return;}if(req.url==="/health/ready"){send(res,200,{status:"ok",service,ready:true},id);return;}
send(res,404,{error:"route_not_implemented",service},id);}
catch(error){errors++;send(res,500,{error:"internal_error",requestId:id},id);log("error","request.failed",{requestId:id},error);}
finally{inFlight--;requests++;const duration=Number(process.hrtime.bigint()-started)/1e6;totalMs+=duration;log("info","http.request",{requestId:id,traceparent:trace||undefined,method:req.method,path:req.url,status:res.statusCode,durationMs:Math.round(duration*10)/10});}}).listen(port,"0.0.0.0",()=>log("info","service.started",{port}));