apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccounts.yaml
  - api-deployment.yaml
  - api-service.yaml
  - worker-core-deployment.yaml
  - network-policy.yaml
  - pod-disruption-budget.yaml
  - autoscaling.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: gestione-dispensa
      app.kubernetes.io/managed-by: kustomize
