apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: dispensa-api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dispensa-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: dispensa-worker-core
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dispensa-worker-core
