apiVersion: v1
kind: ServiceAccount
metadata:
  name: dispensa-api
  labels:
    app.kubernetes.io/name: dispensa-api
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dispensa-worker-core
  labels:
    app.kubernetes.io/name: dispensa-worker-core
automountServiceAccountToken: false
