import express, { type Request } from "express";
import { Pool } from "pg";
const app=express();app.disable("x-powered-by");app.use(express.json({limit:"2mb"}));
const pool=new Pool({connectionString:process.env.DATABASE_URL});const s="nutrition_domain";const port=Number(process.env.PORT??3402);
const scalable=new Set(["g","kg","ml","l"]);
app.get("/health/live",(_,r)=>r.json({status:"ok",service:"service-nutrition"}));app.get("/health/ready",async(_,r)=>{try{await pool.query("select 1");r.json({status:"ok",db:true})}catch{r.status(503).json({status:"not_ready",db:false})}});
function since(period:string){const d=new Date();if(period==="week")d.setUTCDate(d.getUTCDate()-7);else d.setUTCHours(0,0,0,0);return d;}
async function summary(familyId:string,period:"today"|"week"){const q=await pool.query(`select m.id movement_id,p.id product_id,p.canonical_name product_name,m.quantity,m.unit,m.occurred_at,p.calories_per_100,p.protein_per_100,p.carbs_per_100,p.fat_per_100,p.fiber_per_100,p.nutrition_confidence from public.stock_movements m join public.stock_items si on si.id=m.stock_item_id join public.products p on p.id=si.product_id where m.family_id=$1 and m.kind='CONSUMPTION' and m.occurred_at >= $2 order by m.occurred_at desc limit 500`,[familyId,since(period)]);const items=q.rows.map((x:any)=>{const factor=scalable.has(x.unit)&&x.calories_per_100!=null?Number(x.quantity)/100:0;const n=(v:any)=>Math.round((Number(v??0)*factor)*100)/100;return {movementId:x.movement_id,productId:x.product_id,productName:x.product_name,quantity:Number(x.quantity),unit:x.unit,occurredAt:x.occurred_at,confidence:factor?x.nutrition_confidence:"UNKNOWN",nutrients:{calories:n(x.calories_per_100),protein:n(x.protein_per_100),carbs:n(x.carbs_per_100),fat:n(x.fat_per_100),fiber:n(x.fiber_per_100)}}});const totals=items.reduce((a:any,x:any)=>{a.calories+=x.nutrients.calories;a.protein+=x.nutrients.protein;a.carbs+=x.nutrients.carbs;a.fat+=x.nutrients.fat;a.fiber+=x.nutrients.fiber;return a},{calories:0,protein:0,carbs:0,fat:0,fiber:0});return {since:since(period).toISOString(),period,totals,items};}
app.get("/api/v1/nutrition/summary",async(req,res,next)=>{try{const fid=String(req.query.familyId??"");if(!fid)return res.status(400).json({error:{code:"VALIDATION_ERROR",message:"familyId is required"}});const period=req.query.period==="week"?"week":"today";res.json({data:await summary(fid,period)});}catch(e){next(e)}});
app.get("/api/v1/nutrition/today",async(req,res,next)=>{try{const fid=String(req.query.familyId??"");if(!fid)return res.status(400).json({error:{code:"VALIDATION_ERROR"}});res.json({data:await summary(fid,"today")});}catch(e){next(e)}});
app.get("/api/v1/nutrition/history",async(req,res,next)=>{try{const fid=String(req.query.familyId??"");const days=Math.min(Math.max(Number(req.query.days??30),1),365);const d=new Date();d.setUTCDate(d.getUTCDate()-days);const q=await pool.query(`select log_date,coalesce(sum(calories),0)::numeric calories,coalesce(sum(protein_grams),0)::numeric protein,coalesce(sum(carbs_grams),0)::numeric carbs,coalesce(sum(fat_grams),0)::numeric fat from ${s}.nutrition_logs where family_id=$1 and log_date >= $2 group by log_date order by log_date desc`,[fid,d.toISOString().slice(0,10)]);res.json({data:q.rows});}catch(e){next(e)}});
app.get("/api/v1/nutrition/targets",async(req,res,next)=>{try{const fid=String(req.query.familyId??"");const uid=String(req.query.userId??"");if(!uid)return res.status(400).json({error:{code:"VALIDATION_ERROR",message:"userId is required"}});const q=await pool.query(`select * from ${s}.nutrition_targets where user_id=$1 order by updated_at desc limit 1`,[uid]);res.json({data:q.rows[0]??null});}catch(e){next(e)}});
app.put("/api/v1/nutrition/targets",async(req,res,next)=>{try{const b=req.body??{};if(!b.userId)return res.status(400).json({error:{code:"VALIDATION_ERROR",message:"userId is required"}});const q=await pool.query(`insert into ${s}.nutrition_targets(user_id,daily_calories,protein_grams,carbs_grams,fat_grams,diet_type) values($1,$2,$3,$4,$5,$6) on conflict(user_id) do update set daily_calories=excluded.daily_calories,protein_grams=excluded.protein_grams,carbs_grams=excluded.carbs_grams,fat_grams=excluded.fat_grams,diet_type=excluded.diet_type,updated_at=now() returning *`,[b.userId,b.dailyCalories??2000,b.proteinGrams??150,b.carbsGrams??200,b.fatGrams??65,b.dietType??"STANDARD"]);res.json({data:q.rows[0]});}catch(e){next(e)}});
app.post("/api/v1/nutrition/log",async(req,res,next)=>{try{const b=req.body??{};if(!b.familyId||!b.userId)return res.status(400).json({error:{code:"VALIDATION_ERROR",message:"familyId and userId are required"}});const q=await pool.query(`insert into ${s}.nutrition_logs(family_id,user_id,log_date,calories,protein_grams,carbs_grams,fat_grams,fiber_grams,source_type,source_ref) values($1,$2,coalesce($3::date,current_date),$4,$5,$6,$7,$8,$9,$10) returning *`,[b.familyId,b.userId??null,b.logDate??null,b.calories??0,b.proteinGrams??0,b.carbsGrams??0,b.fatGrams??0,b.fiberGrams??0,b.source??"MANUAL",b.sourceRef??null]);res.status(201).json({data:q.rows[0]});}catch(e){next(e)}});
app.get("/api/v1/nutrition",async(req,res,next)=>{try{const fid=String(req.query.familyId??"");res.json({data:{today:await summary(fid,"today")}})}catch(e){next(e)}});
app.use((e:any,_q:Request,r:any,_n:any)=>r.status(e?.code==="23505"?409:500).json({error:{code:e?.code==="23505"?"CONFLICT":"INTERNAL_ERROR",message:e?.message??"Internal error"}}));
app.listen(port,"0.0.0.0",()=>process.stdout.write(JSON.stringify({service:"service-nutrition",port})+"\n"));
