import express from "express";import {Pool} from "pg";import crypto from "node:crypto";
const app=express();app.use(express.json({limit:"1mb"}));const port=Number(process.env.PORT??3402);const pool=new Pool({connectionString:process.env.DATABASE_URL});
const fail=(res:express.Response,s:number,c:string,m:string)=>res.status(s).json({error:{code:c,message:m,details:[],requestId:crypto.randomUUID()}});
async function init(){await pool.query(`create schema if not exists nutrition_domain`);await pool.query(`create table if not exists nutrition_domain.targets(user_id uuid primary key,calories_kcal numeric not null,protein_g numeric not null,carbs_g numeric not null,fat_g numeric not null,version integer not null default 1)`);await pool.query(`create table if not exists nutrition_domain.diary(id uuid primary key,user_id uuid not null,date date not null,meal varchar(32) not null,product_id uuid not null,quantity numeric not null,unit varchar(16) not null,source varchar(32) not null,version integer not null default 1,created_at timestamptz not null default now())`);}
app.get("/health/live",(_q,r)=>r.json({status:"ok",service:"service-nutrition"}));app.get("/health/ready",async(_q,r)=>{try{await pool.query("select 1");r.json({status:"ready"})}catch{r.status(503).json({status:"not_ready"})}});
const user=(req:express.Request)=>String(req.header("x-user-id")??"");
const targetDto=(x:any)=>({caloriesKcal:Number(x.calories_kcal),proteinG:Number(x.protein_g),carbsG:Number(x.carbs_g),fatG:Number(x.fat_g),version:x.version});
app.get("/api/v1/nutrition/targets",async(req,res)=>{const u=user(req);if(!u)return fail(res,401,"UNAUTHENTICATED","Authenticated user required.");let q=await pool.query("select * from nutrition_domain.targets where user_id=$1",[u]);if(!q.rowCount){q=await pool.query("insert into nutrition_domain.targets(user_id,calories_kcal,protein_g,carbs_g,fat_g) values($1,2000,100,250,70) returning *",[u])}res.json({data:targetDto(q.rows[0])})});
app.put("/api/v1/nutrition/targets",async(req,res)=>{const u=user(req),b=req.body??{};if(!u)return fail(res,401,"UNAUTHENTICATED","Authenticated user required.");for(const k of ["caloriesKcal","proteinG","carbsG","fatG"])if(!Number.isFinite(Number(b[k]))||Number(b[k])<0)return fail(res,400,"VALIDATION_ERROR",`${k} must be non-negative.`);const q=await pool.query(`insert into nutrition_domain.targets(user_id,calories_kcal,protein_g,carbs_g,fat_g) values($1,$2,$3,$4,$5) on conflict(user_id) do update set calories_kcal=excluded.calories_kcal,protein_g=excluded.protein_g,carbs_g=excluded.carbs_g,fat_g=excluded.fat_g,version=nutrition_domain.targets.version+1 returning *`,[u,b.caloriesKcal,b.proteinG,b.carbsG,b.fatG]);res.json({data:targetDto(q.rows[0]),version:q.rows[0].version})});
app.get("/api/v1/nutrition/diary",async(req,res)=>{const u=user(req);if(!u)return fail(res,401,"UNAUTHENTICATED","Authenticated user required.");const q=await pool.query("select * from nutrition_domain.diary where user_id=$1 and ($2='' or date >= $2::date) and ($3='' or date <= $3::date) order by date desc,created_at desc limit $4",[u,String(req.query.from??""),String(req.query.to??""),Math.min(Math.max(Number(req.query.limit??50),1),100)]);res.json({items:q.rows.map(x=>({entryId:x.id,date:x.date,meal:x.meal,productId:x.product_id,quantity:Number(x.quantity),unit:x.unit,source:x.source})),nextCursor:null})});
app.post("/api/v1/nutrition/diary",async(req,res)=>{const u=user(req),b=req.body??{};if(!u)return fail(res,401,"UNAUTHENTICATED","Authenticated user required.");if(!b.date||!b.meal||!b.productId||!Number.isFinite(Number(b.quantity))||Number(b.quantity)<=0||!b.unit)return fail(res,400,"VALIDATION_ERROR","date, meal, productId, quantity and unit are required.");const id=crypto.randomUUID();const q=await pool.query("insert into nutrition_domain.diary(id,user_id,date,meal,product_id,quantity,unit,source) values($1,$2,$3,$4,$5,$6,$7,$8) returning *",[id,u,b.date,b.meal,b.productId,b.quantity,b.unit,b.source??"manual"]);const x=q.rows[0];res.status(201).json({data:{entryId:x.id,date:x.date,meal:x.meal,productId:x.product_id,quantity:Number(x.quantity),unit:x.unit,source:x.source},version:x.version})});
app.get("/api/v1/nutrition/summary",async(req,res)=>{const u=user(req);if(!u)return fail(res,401,"UNAUTHENTICATED","Authenticated user required.");const t=await pool.query("select * from nutrition_domain.targets where user_id=$1",[u]);res.json({data:{caloriesKcal:t.rowCount?Number(t.rows[0].calories_kcal):2000,proteinG:t.rowCount?Number(t.rows[0].protein_g):100,carbsG:t.rowCount?Number(t.rows[0].carbs_g):250,fatG:t.rowCount?Number(t.rows[0].fat_g):70,period:String(req.query.period??"today")}})});
app.use((_q,r)=>fail(r,404,"NOT_FOUND","Route not found."));init().then(()=>app.listen(port,"0.0.0.0",()=>console.log(JSON.stringify({service:"service-nutrition",port}))).catch(e=>{console.error(e);process.exit(1)});
