CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS families(id uuid PRIMARY KEY,name varchar(120) NOT NULL CHECK(length(trim(name))>0),created_by_user_id uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),version integer NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS members(id uuid PRIMARY KEY,family_id uuid NOT NULL REFERENCES families(id) ON DELETE CASCADE,user_id uuid NOT NULL,role varchar(16) NOT NULL CHECK(role IN ('owner','admin','member')),joined_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),version integer NOT NULL DEFAULT 1,UNIQUE(family_id,user_id));
CREATE TABLE IF NOT EXISTS invites(id uuid PRIMARY KEY,family_id uuid NOT NULL REFERENCES families(id) ON DELETE CASCADE,email varchar(320) NOT NULL,role varchar(16) NOT NULL CHECK(role IN ('admin','member')),token_hash varchar(128) UNIQUE NOT NULL,status varchar(16) NOT NULL CHECK(status IN ('pending','accepted','revoked','expired')),expires_at timestamptz NOT NULL,accepted_by_user_id uuid NULL,accepted_at timestamptz NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),version integer NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS outbox_events(id uuid PRIMARY KEY,event_id uuid UNIQUE NOT NULL,event_type varchar(128) NOT NULL,schema_version integer NOT NULL,aggregate_id uuid NOT NULL,family_id uuid NULL,correlation_id uuid NOT NULL,causation_id uuid NULL,occurred_at timestamptz NOT NULL,payload jsonb NOT NULL,published_at timestamptz NULL,attempts integer NOT NULL DEFAULT 0,last_error text NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS members_user_idx ON members(user_id);
CREATE INDEX IF NOT EXISTS invites_family_status_idx ON invites(family_id,status);
CREATE INDEX IF NOT EXISTS outbox_publish_idx ON outbox_events(published_at,created_at);
CREATE TABLE IF NOT EXISTS idempotency_keys(key varchar(255) PRIMARY KEY,actor_user_id uuid NOT NULL,family_id uuid NULL,request_hash varchar(64) NOT NULL,status varchar(16) NOT NULL CHECK(status IN ('processing','completed','failed')),response_status integer,response_body jsonb,created_at timestamptz NOT NULL DEFAULT now(),expires_at timestamptz NOT NULL);
