import { useState } from "react";
import AuthShell from "./AuthShell";
import type { AuthUser } from "../../store/auth";
import { colors } from "../../tokens";
import { Input } from "../../components/ui/Input";
import { KEYCLOAK_REALM_URL, KEYCLOAK_CLIENT_ID } from "../../api/config";
import { useAuthStore } from "../../store/auth";
import { registerUser, getCurrentUser, listFamilies } from "../../api/endpoints";
import { ApiError } from "../../api/client";
type Step="form"|"submitting"|"done"; interface Props{onRegistered:(user:AuthUser)=>void;onLogin:()=>void;}
function normalizeRole(role:string|undefined):AuthUser["role"]{switch(role?.toLowerCase()){case"owner":return"OWNER";case"admin":case"manager":return"MANAGER";case"viewer":return"VIEWER";default:return"MEMBER";}}
export default function Register({onRegistered,onLogin}:Props){const[step,setStep]=useState<Step>("form"),[name,setName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[showPw,setShowPw]=useState(false),[apiError,setApiError]=useState<string|null>(null);const setTokens=useAuthStore(s=>s.setTokens);
async function handleSubmit(e:React.FormEvent){e.preventDefault();setApiError(null);if(!name.trim()||!email.includes("@")||password.length<8||password!==confirm){setApiError("Controlla nome, email e password (almeno 8 caratteri; le password devono coincidere).");return;}setStep("submitting");const cleanEmail=email.trim().toLowerCase(),cleanName=name.trim();try{try{await registerUser({name:cleanName,email:cleanEmail,password});}catch(error){if(!(error instanceof ApiError)||error.code!=="USER_ALREADY_EXISTS")throw error;}if(!KEYCLOAK_REALM_URL||!KEYCLOAK_CLIENT_ID)throw new Error("Configurazione OIDC non disponibile. Contatta l'amministratore.");const tokenRes=await fetch(`${KEYCLOAK_REALM_URL}/protocol/openid-connect/token`,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"password",client_id:KEYCLOAK_CLIENT_ID,username:cleanEmail,password,scope:"openid profile email"})});const tokenData=await tokenRes.json().catch(()=>({}));if(!tokenRes.ok||!tokenData.access_token)throw new Error(tokenData.error_description||"Account creato, ma impossibile completare l'accesso automatico.");if(!tokenData.refresh_token)throw new Error("Account creato, ma Keycloak non ha emesso un refresh token.");setTokens({accessToken:tokenData.access_token,refreshToken:tokenData.refresh_token,expiresIn:typeof tokenData.expires_in==="number"?tokenData.expires_in:300});const user=await getCurrentUser();const families=await listFamilies();const active=user.activeFamilyId?families.families.find(f=>f.familyId===user.activeFamilyId):families.families[0];const displayName=user.displayName||cleanName;const authUser:AuthUser={id:user.userId,name:displayName,email:user.email||cleanEmail,avatar:displayName.slice(0,2).toUpperCase(),role:normalizeRole(active?.role),hasFamilyId:active?.familyId??null};setStep("done");onRegistered(authUser);}catch(err){setStep("form");setApiError(err instanceof Error?err.message:"Errore durante la registrazione. Riprova.");}}
return <AuthShell title="Crea account" subtitle="Inizia a gestire la dispensa di famiglia">{step==="done"?<div className="text-center space-y-4 py-4"><div className="text-5xl">✓</div><p className="font-medium" style={{color:colors.sageDark}}>Account creato!</p><p className="text-sm" style={{color:colors.inkMuted}}>Configurazione della tua famiglia…</p></div>:<form onSubmit={handleSubmit} className="space-y-4">{apiError&&<div className="rounded-xl px-4 py-3 text-sm" style={{backgroundColor:colors.terracottaLight,color:colors.terracotta}}>{apiError}</div>}<Input label="Nome completo" type="text" value={name} onChange={e=>setName(e.target.value)} placeholder="Es. Giulia Ferretti" autoComplete="name" required/><Input label="Email" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="nome@esempio.it" autoComplete="email" required/><div className="relative"><Input label="Password" type={showPw?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Almeno 8 caratteri" autoComplete="new-password" required/><button type="button" onClick={()=>setShowPw(v=>!v)} className="absolute right-3 top-8 text-xs" style={{color:colors.inkMuted}}>{showPw?"Nascondi":"Mostra"}</button></div><Input label="Conferma password" type={showPw?"text":"password"} value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Ripeti la password" autoComplete="new-password" required/><p className="text-[10px]" style={{color:colors.inkMuted}}>Continuando accetti i Termini di servizio e la Privacy Policy.</p><button type="submit" disabled={step==="submitting"} className="w-full py-3 rounded-xl text-sm font-semibold" style={{backgroundColor:step==="submitting"?colors.border:colors.terracotta,color:colors.white}}>{step==="submitting"?"Creazione account…":"Crea account"}</button></form>} {step==="form"&&<div className="text-center mt-4"><span className="text-xs" style={{color:colors.inkMuted}}>Hai già un account? </span><button type="button" onClick={onLogin} className="text-xs font-semibold" style={{color:colors.terracotta}}>Accedi</button></div>}</AuthShell>}
