BEGIN;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'dispensa_app') THEN
    CREATE ROLE dispensa_app NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'dispensa_worker') THEN
    CREATE ROLE dispensa_worker NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT BYPASSRLS;
  END IF;
END
$$;

ALTER ROLE dispensa_app NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
ALTER ROLE dispensa_worker NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT BYPASSRLS;
REVOKE CREATE ON SCHEMA public FROM dispensa_app, dispensa_worker;
GRANT USAGE ON SCHEMA public TO dispensa_app, dispensa_worker;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO dispensa_app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO dispensa_app;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO dispensa_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO dispensa_worker;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO dispensa_worker;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO dispensa_worker;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO dispensa_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO dispensa_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO dispensa_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO dispensa_worker;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO dispensa_worker;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO dispensa_worker;
CREATE OR REPLACE FUNCTION public.app_is_service() RETURNS boolean LANGUAGE sql STABLE AS $$ SELECT false $$;
COMMIT;
