import express, { type Request } from "express";
import { Pool } from "pg";
const app=express();app.disable("x-powered-by");app.use(express.json({limit:"1mb"}));const pool=new Pool({connectionString:process.env.DATABASE_URL});const s="shelf_life_domain";const port=Number(process.env.PORT??3404);
type StorageKind="PANTRY"|"FRIDGE"|"FREEZER"|"CELLAR"|"OTHER";
const normalize=(v:any):StorageKind=>{const x=String(v??"").trim().toLowerCase();if(["frigo","fridge","frigorifero"].includes(x))return"FRIDGE";if(["freezer","congelatore"].includes(x))return"FREEZER";if(["dispensa","pantry"].includes(x))return"PANTRY";if(["cantina","cellar"].includes(x))return"CELLAR";return"OTHER"};
async function resolve(category:string|undefined,storage:StorageKind){const q=await pool.query(`select category,storage_kind,estimated_days,notify_days_before,source from ${s}.rules where category=$1 and storage_kind=$2 union all select category,storage_kind,estimated_days,notify_days_before,source from ${s}.rules where category='__default__' and storage_kind=$2 limit 1`,[category?.trim().toLowerCase()||"__default__",storage]);return q.rows[0] as any|undefined;}
async function predict(category:string|undefined,storage:StorageKind,receivedAt:string|Date){const rule=await resolve(category,storage);if(!rule||rule.estimated_days==null)return{estimated:false,expirationDate:null,notifyDaysBefore:Number(rule?.notify_days_before??2)};const d=new Date(receivedAt);d.setUTCDate(d.getUTCDate()+Number(rule.estimated_days));return{estimated:true,expirationDate:d.toISOString().slice(0,10),estimatedDays:Number(rule.estimated_days),notifyDaysBefore:Number(rule.notify_days_before),source:rule.source};}
app.get("/api/v1/shelf-life/predictions",async(req,res)=>{const itemId=String(req.query.itemId??"");const productId=String(req.query.productId??"");const q=await pool.query(`select * from ${s}.predictions where ($1='' or item_id=$1) and ($2='' or product_id=$2) order by created_at desc limit 100`,[itemId,productId]);res.json({items:q.rows,nextCursor:null})});
app.post("/api/v1/shelf-life/predictions",async(req,res)=>{const b=req.body??{};if(!b.itemId||!b.productId)return res.status(400).json({error:{code:"VALIDATION_ERROR",message:"itemId and productId are required."}});const p=await predict(b.category,normalize(b.storageKind),b.receivedAt??new Date().toISOString());if(!p.expirationDate)return res.status(422).json({error:{code:"PREDICTION_UNAVAILABLE",message:"No shelf-life rule is available."}});const q=await pool.query(`insert into ${s}.predictions(item_id,product_id,estimated_expires_at,confidence,basis,model_version,status) values($1,$2,$3,$4,$5,$6,'completed') returning *`,[b.itemId,b.productId,p.expirationDate,Number(b.confidence??0.5),p.source??"rule","rule-v1"]);res.status(201).json({data:q.rows[0],version:q.rows[0].version})});
app.get("/api/v1/shelf-life/predictions/:predictionId",async(req,res)=>{const q=await pool.query(`select * from ${s}.predictions where id=$1`,[req.params.predictionId]);if(!q.rowCount)return res.status(404).json({error:{code:"NOT_FOUND",message:"Prediction not found."}});res.json({data:q.rows[0]})});
app.post("/api/v1/shelf-life/predictions/:predictionId/apply",async(req,res)=>{const q=await pool.query(`update ${s}.predictions set status='applied',version=version+1,updated_at=now() where id=$1 and status in ('completed','queued') returning *`,[req.params.predictionId]);if(!q.rowCount)return res.status(404).json({error:{code:"NOT_FOUND",message:"Prediction not found or already applied."}});res.json({data:q.rows[0],version:q.rows[0].version})});
app.get("/health/live",(_,r)=>r.json({status:"ok",service:"service-shelf-life"}));app.get("/health/ready",async(_,r)=>{try{await pool.query("select 1");r.json({status:"ok",db:true})}catch{r.status(503).json({status:"not_ready",db:false})}});
app.use((e:any,_q:Request,r:any,_n:any)=>r.status(500).json({error:{code:"INTERNAL_ERROR",message:e?.message??"Internal error"}}));
async function ensureSchema(){await pool.query(`create schema if not exists ${s}`);await pool.query(`create table if not exists ${s}.predictions(id uuid primary key default gen_random_uuid(),item_id uuid not null,product_id uuid not null,estimated_expires_at timestamptz not null,confidence numeric(5,4) not null,basis text not null,model_version varchar(64) not null,status varchar(32) not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),version integer not null default 1)`);
await pool.query(`create table if not exists ${s}.rules(id uuid primary key default gen_random_uuid(),category text not null,storage_kind text not null,estimated_days integer,notify_days_before integer not null default 2,source text not null default 'DEFAULT',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(category,storage_kind))`);for(const k of ["PANTRY","FRIDGE","FREEZER","CELLAR","OTHER"])await pool.query(`insert into ${s}.rules(category,storage_kind,estimated_days,notify_days_before,source) values('__default__',$1,null,2,'DEFAULT') on conflict do nothing`,[k]);}
await ensureSchema();
app.listen(port,"0.0.0.0",()=>process.stdout.write(JSON.stringify({service:"service-shelf-life",port})+"\n"));
