import express, { type Request } from "express";
import { Pool } from "pg";
const app=express();app.disable("x-powered-by");app.use(express.json({limit:"1mb"}));const pool=new Pool({connectionString:process.env.DATABASE_URL});const s="shelf_life_domain";const port=Number(process.env.PORT??3404);
type StorageKind="PANTRY"|"FRIDGE"|"FREEZER"|"CELLAR"|"OTHER";
const normalize=(v:any):StorageKind=>{const x=String(v??"").trim().toLowerCase();if(["frigo","fridge","frigorifero"].includes(x))return"FRIDGE";if(["freezer","congelatore"].includes(x))return"FREEZER";if(["dispensa","pantry"].includes(x))return"PANTRY";if(["cantina","cellar"].includes(x))return"CELLAR";return"OTHER"};
async function resolve(category:string|undefined,storage:StorageKind){const q=await pool.query(`select category,storage_kind,estimated_days,notify_days_before,source from ${s}.rules where category=$1 and storage_kind=$2 union all select category,storage_kind,estimated_days,notify_days_before,source from ${s}.rules where category='__default__' and storage_kind=$2 limit 1`,[category?.trim().toLowerCase()||"__default__",storage]);return q.rows[0] as any|undefined;}
async function predict(category:string|undefined,storage:StorageKind,receivedAt:string|Date){const rule=await resolve(category,storage);if(!rule||rule.estimated_days==null)return{estimated:false,expirationDate:null,notifyDaysBefore:Number(rule?.notify_days_before??2)};const d=new Date(receivedAt);d.setUTCDate(d.getUTCDate()+Number(rule.estimated_days));return{estimated:true,expirationDate:d.toISOString().slice(0,10),estimatedDays:Number(rule.estimated_days),notifyDaysBefore:Number(rule.notify_days_before),source:rule.source};}
app.get("/health/live",(_,r)=>r.json({status:"ok",service:"service-shelf-life"}));app.get("/health/ready",async(_,r)=>{try{await pool.query("select 1");r.json({status:"ok",db:true})}catch{r.status(503).json({status:"not_ready",db:false})}});
app.get("/api/v1/shelf-life/predict",async(req,res,next)=>{try{res.json({data:await predict(req.query.category as string|undefined,normalize(req.query.storageKind),String(req.query.insertedAt??new Date().toISOString()))});}catch(e){next(e)}});
app.post("/api/v1/shelf-life/predict",async(req,res,next)=>{try{const b=req.body??{};res.json({data:await predict(b.category,normalize(b.storageKind),b.receivedAt??b.insertedAt??new Date().toISOString())});}catch(e){next(e)}});
app.get("/api/v1/shelf-life/foodkeeper/categories",async(_,res,next)=>{try{const q=await pool.query(`select distinct category from ${s}.rules order by category`);res.json({data:q.rows.map(x=>x.category)});}catch(e){next(e)}});
app.get("/api/v1/shelf-life/foodkeeper/items/:id",async(req,res,next)=>{try{const q=await pool.query(`select * from ${s}.rules where id=$1`,[req.params.id]);if(!q.rowCount)return res.status(404).json({error:{code:"NOT_FOUND"}});res.json({data:q.rows[0]});}catch(e){next(e)}});
app.post("/api/v1/shelf-life/custom-rule",async(req,res,next)=>{try{const b=req.body??{};const q=await pool.query(`insert into ${s}.rules(category,storage_kind,estimated_days,notify_days_before,source) values($1,$2,$3,$4,'CUSTOM') on conflict(category,storage_kind) do update set estimated_days=excluded.estimated_days,notify_days_before=excluded.notify_days_before,source='CUSTOM',updated_at=now() returning *`,[String(b.category).trim().toLowerCase(),normalize(b.storageKind),b.estimatedDays??null,b.notifyDaysBefore??2]);res.status(201).json({data:q.rows[0]});}catch(e){next(e)}});
app.use((e:any,_q:Request,r:any,_n:any)=>r.status(500).json({error:{code:"INTERNAL_ERROR",message:e?.message??"Internal error"}}));
app.listen(port,"0.0.0.0",()=>process.stdout.write(JSON.stringify({service:"service-shelf-life",port})+"\n"));
