import {createServer,type IncomingMessage,type ServerResponse} from "node:http";import {randomUUID,createHash,randomBytes} from "node:crypto";import {Pool,type PoolClient} from "pg";
const port=Number(process.env.PORT??3311),service="service-family";const pool=new Pool({connectionString:process.env.DATABASE_URL});
type Ctx={userId:string;requestId:string;correlationId:string};const send=(r:ServerResponse,s:number,b:unknown,id:string)=>{r.statusCode=s;r.setHeader("content-type","application/json");r.setHeader("x-request-id",id);r.end(JSON.stringify(b));};const fail=(r:ServerResponse,s:number,c:string,m:string,id:string)=>send(r,s,{error:{code:c,message:m,details:[],requestId:id}},id);
async function body(q:IncomingMessage){let s="";for await(const c of q)s+=c;return s?JSON.parse(s):{};}function ctx(q:IncomingMessage):Ctx|null{const u=String(q.headers["x-user-id"]??"");return u?{userId:u,requestId:String(q.headers["x-request-id"]??randomUUID()),correlationId:String(q.headers["x-correlation-id"]??randomUUID())}:null;}const hash=(x:unknown)=>createHash("sha256").update(JSON.stringify(x)).digest("hex");const tokenHash=(x:string)=>createHash("sha256").update(x).digest("hex");
async function outbox(c:PoolClient,type:string,aggregate:string,family:string|undefined,ctx:Ctx,payload:unknown){const id=randomUUID();await c.query("insert into outbox_events(id,event_id,event_type,schema_version,aggregate_id,family_id,correlation_id,occurred_at,payload) values($1,$1,$2,1,$3,$4,$5,now(),$6)",[id,type,aggregate,family??null,ctx.correlationId,ctx.correlationId,JSON.stringify(payload)]);}
async function idem(c:PoolClient,key:string,ctx:Ctx,b:unknown){if(!key)return null;const h=hash(b),q=await c.query("select * from idempotency_keys where key=$1 for update",[key]);if(q.rowCount){const r=q.rows[0];if(r.actor_user_id!==ctx.userId||r.request_hash!==h)return {conflict:true};if(r.status==="completed")return {status:r.response_status,body:r.response_body};return null;}await c.query("insert into idempotency_keys(key,actor_user_id,request_hash,status,expires_at) values($1,$2,$3,'processing',now()+interval '24 hours')",[key,ctx.userId,h]);return null;}async function done(c:PoolClient,k:string,s:number,b:unknown){if(k)await c.query("update idempotency_keys set status='completed',response_status=$2,response_body=$3 where key=$1",[k,s,JSON.stringify(b)]);}
async function role(c:PoolClient,f:string,u:string){const q=await c.query("select role from members where family_id=$1 and user_id=$2",[f,u]);return q.rowCount?(q.rows[0].role as string):null;}function can(r:string|null,w:boolean){return !!r&&(!w||r==="owner"||r==="admin");}
const server=createServer(async(req,res)=>{const rid=String(req.headers["x-request-id"]??randomUUID());try{if(req.url==="/health/live")return send(res,200,{status:"ok",service},rid);if(req.url==="/health/ready"){await pool.query("select 1");return send(res,200,{status:"ready",service},rid);}const cctx=ctx(req);if(!cctx)return fail(res,401,"UNAUTHENTICATED","Missing authenticated user context.",rid);const u=new URL(req.url??"/","http://family"),p=u.pathname;
if(req.method==="GET"&&p==="/api/v1/families"){const q=await pool.query("select f.id,f.name,f.created_at,m.role,(select count(*) from members x where x.family_id=f.id) member_count from families f join members m on m.family_id=f.id where m.user_id=$1 order by f.created_at desc limit 100",[cctx.userId]);return send(res,200,{items:q.rows.map(x=>({familyId:x.id,name:x.name,role:x.role,memberCount:Number(x.member_count),createdAt:x.created_at})),nextCursor:null},cctx.requestId);}
if(req.method==="POST"&&p==="/api/v1/families"){const b=await body(req),name=String(b.name??"").trim(),k=String(req.headers["x-idempotency-key"]??"");if(!name)return fail(res,400,"VALIDATION_ERROR","name is required.",cctx.requestId);const c=await pool.connect();try{await c.query("begin");const old=await idem(c,k,cctx,b);if(old?.conflict){await c.query("rollback");return fail(res,409,"CONFLICT","Idempotency key conflict.",cctx.requestId);}if(old?.body){await c.query("commit");return send(res,old.status,old.body,cctx.requestId);}const id=randomUUID();await c.query("insert into families(id,name,created_by_user_id) values($1,$2,$3)",[id,name,cctx.userId]);await c.query("insert into members(id,family_id,user_id,role,joined_at) values($1,$2,$3,'owner',now())",[randomUUID(),id,cctx.userId]);const out={data:{familyId:id,name,role:"owner",createdAt:new Date().toISOString()},version:1};await outbox(c,"FamilyCreated",id,id,cctx,out);await done(c,k,201,out);await c.query("commit");return send(res,201,out,cctx.requestId);}catch(e){await c.query("rollback");throw e}finally{c.release();}}
const fm=p.match(/^\/api\/v1\/families\/([0-9a-f-]+)(?:\/(members|invites))?(?:\/([0-9a-f-]+))?$/i);
if(fm){const fid=fm[1],sub=fm[2],sid=fm[3],r=await role(pool,fid,cctx.userId);if(!r)return fail(res,403,"FORBIDDEN","User is not a family member.",cctx.requestId);
if(req.method==="GET"&&!sub){const q=await pool.query("select f.*,m.role from families f join members m on m.family_id=f.id and m.user_id=$2 where f.id=$1",[fid,cctx.userId]);const ms=await pool.query("select m.user_id,m.role,m.joined_at,i.display_name from members m left join (select null::uuid as user_id,null::text as display_name where false) i on false where m.family_id=$1 order by m.joined_at",[fid]);return send(res,200,{data:{familyId:q.rows[0].id,name:q.rows[0].name,members:ms.rows.map(x=>({userId:x.user_id,displayName:null,role:x.role,joinedAt:x.joined_at})),version:q.rows[0].version}},cctx.requestId);}
if(req.method==="PATCH"&&!sub){if(!can(r,true))return fail(res,403,"FORBIDDEN","Admin or owner role required.",cctx.requestId);const b=await body(req);if(!b.name)return fail(res,400,"VALIDATION_ERROR","name is required.",cctx.requestId);const k=String(req.headers["x-idempotency-key"]??"");const q=await pool.query("update families set name=$2,updated_at=now(),version=version+1 where id=$1 returning *",[fid,String(b.name).trim()]);return send(res,200,{data:{familyId:fid,name:q.rows[0].name,version:q.rows[0].version},version:q.rows[0].version},cctx.requestId);}
if(req.method==="DELETE"&&!sub){if(r!=="owner")return fail(res,403,"FORBIDDEN","Owner role required.",cctx.requestId);await pool.query("delete from families where id=$1",[fid]);return send(res,204,null,cctx.requestId);}
if(sub==="members"&&req.method==="GET"&&!sid){const q=await pool.query("select user_id,role,joined_at from members where family_id=$1 order by joined_at",[fid]);return send(res,200,{items:q.rows.map(x=>({userId:x.user_id,role:x.role,joinedAt:x.joined_at})),nextCursor:null},cctx.requestId);}
if(sub==="members"&&sid&&req.method==="PATCH"){if(!can(r,true)||sid===cctx.userId)return fail(res,403,"FORBIDDEN","Insufficient family role.",cctx.requestId);const b=await body(req);if(!["admin","member"].includes(b.role))return fail(res,400,"VALIDATION_ERROR","role must be admin or member.",cctx.requestId);const q=await pool.query("update members set role=$3,updated_at=now(),version=version+1 where family_id=$1 and user_id=$2 and role<>'owner' returning user_id,role,joined_at,version",[fid,sid,b.role]);if(!q.rowCount)return fail(res,404,"NOT_FOUND","Member not found.",cctx.requestId);return send(res,200,{data:{userId:q.rows[0].user_id,role:q.rows[0].role,joinedAt:q.rows[0].joined_at},version:q.rows[0].version},cctx.requestId);}
if(sub==="members"&&sid&&req.method==="DELETE"){if(!can(r,true)||sid===cctx.userId)return fail(res,403,"FORBIDDEN","Insufficient family role.",cctx.requestId);const q=await pool.query("delete from members where family_id=$1 and user_id=$2 and role<>'owner'",[fid,sid]);return q.rowCount?send(res,204,null,cctx.requestId):fail(res,404,"NOT_FOUND","Member not found.",cctx.requestId);}
if(sub==="invites"&&req.method==="GET"&&!sid){const q=await pool.query("select id,email,role,status,expires_at,created_at from invites where family_id=$1 order by created_at desc limit 100",[fid]);return send(res,200,{items:q.rows.map(x=>({inviteId:x.id,email:x.email,role:x.role,status:x.status,expiresAt:x.expires_at,createdAt:x.created_at})),nextCursor:null},cctx.requestId);}
if(sub==="invites"&&req.method==="POST"&&!sid){if(!can(r,true))return fail(res,403,"FORBIDDEN","Admin or owner role required.",cctx.requestId);const b=await body(req),email=String(b.email??"").trim().toLowerCase(),rr=String(b.role??"member"),secs=Math.max(3600,Math.min(604800,Number(b.expiresInSeconds??86400)));if(!email||!["admin","member"].includes(rr))return fail(res,400,"VALIDATION_ERROR","Invalid invite.",cctx.requestId);const raw=randomBytes(32).toString("hex"),id=randomUUID(),q=await pool.query("insert into invites(id,family_id,email,role,token_hash,status,expires_at) values($1,$2,$3,$4,$5,'pending',now()+make_interval(secs=>$6)) returning *",[id,fid,email,rr,tokenHash(raw),secs]);return send(res,201,{data:{inviteId:id,email,role:rr,status:"pending",expiresAt:q.rows[0].expires_at,inviteToken:raw},version:1},cctx.requestId);}
if(sub==="invites"&&sid&&req.method==="DELETE"){if(!can(r,true))return fail(res,403,"FORBIDDEN","Admin or owner role required.",cctx.requestId);const q=await pool.query("update invites set status='revoked',updated_at=now(),version=version+1 where id=$1 and family_id=$2 and status='pending' returning id",[sid,fid]);return q.rowCount?send(res,204,null,cctx.requestId):fail(res,404,"NOT_FOUND","Invite not found.",cctx.requestId);}
}
if(req.method==="GET"&&p.startsWith("/api/v1/family-invites/")){const token=p.split("/").pop()!,q=await pool.query("select i.id,i.email,i.role,i.status,i.expires_at,f.name family_name from invites i join families f on f.id=i.family_id where i.token_hash=$1",[tokenHash(token)]);if(!q.rowCount)return fail(res,404,"NOT_FOUND","Invite not found.",cctx.requestId);const x=q.rows[0];if(x.status==="pending"&&new Date(x.expires_at)<new Date()){await pool.query("update invites set status='expired' where id=$1",[x.id]);x.status="expired";}return send(res,200,{data:{inviteId:x.id,familyName:x.family_name,role:x.role,status:x.status,expiresAt:x.expires_at}},cctx.requestId);}
if(req.method==="POST"&&p.startsWith("/api/v1/family-invites/")&&p.endsWith("/accept")){const token=p.split("/")[4];const c=await pool.connect();try{await c.query("begin");const q=await c.query("select i.*,f.name family_name from invites i join families f on f.id=i.family_id where i.token_hash=$1 for update",[tokenHash(token)]);if(!q.rowCount){await c.query("rollback");return fail(res,404,"NOT_FOUND","Invite not found.",cctx.requestId);}const x=q.rows[0];if(x.status!=="pending"||new Date(x.expires_at)<new Date()){await c.query("rollback");return fail(res,409,"INVITE_INVALID","Invite is no longer valid.",cctx.requestId);}const m=await c.query("insert into members(id,family_id,user_id,role,joined_at) values($1,$2,$3,$4,now()) on conflict(family_id,user_id) do update set role=excluded.role,updated_at=now(),version=members.version+1 returning *",[randomUUID(),x.family_id,cctx.userId,x.role]);await c.query("update invites set status='accepted',accepted_by_user_id=$2,accepted_at=now(),updated_at=now(),version=version+1 where id=$1",[x.id,cctx.userId]);const out={data:{familyId:x.family_id,userId:cctx.userId,role:m.rows[0].role,joinedAt:m.rows[0].joined_at},version:m.rows[0].version};await outbox(c,"FamilyInviteAccepted",x.family_id,x.family_id,cctx,out);await c.query("commit");return send(res,201,out,cctx.requestId);}catch(e){await c.query("rollback");throw e}finally{c.release();}}
return fail(res,404,"NOT_FOUND","Route not found.",cctx.requestId);}catch(e){console.error(JSON.stringify({service,error:String(e)}));return fail(res,500,"INTERNAL_ERROR","Unexpected internal error.",rid);}});server.listen(port,"0.0.0.0",()=>console.log(JSON.stringify({service,port})));