import {createServer,type IncomingMessage,type ServerResponse} from "node:http";
import {randomUUID,createHash} from "node:crypto";
import {Pool,type PoolClient} from "pg";

const port=Number(process.env.PORT??3312);
const service="service-inventory";
const pool=new Pool({connectionString:process.env.DATABASE_URL??"postgres://inventory:inventory@postgres:5432/inventory_db"});
const familyServiceBaseUrl=(process.env.FAMILY_SERVICE_BASE_URL??"http://service-family:3311/api/v1").replace(/\/$/,"");
type Ctx={userId:string;familyId:string;requestId:string;correlationId:string};
const send=(r:ServerResponse,s:number,b:unknown,id:string)=>{r.statusCode=s;r.setHeader("content-type","application/json");r.setHeader("x-request-id",id);r.end(JSON.stringify(b));};
const fail=(r:ServerResponse,s:number,c:string,m:string,id:string)=>send(r,s,{error:{code:c,message:m,details:[],requestId:id}},id);
async function body(req:IncomingMessage){let x="";for await(const c of req)x+=c;return x?JSON.parse(x):{};}
function ctx(req:IncomingMessage):Ctx|null{const userId=String(req.headers["x-user-id"]??""),familyId=String(req.headers["x-family-id"]??"");return userId&&familyId?{userId,familyId,requestId:String(req.headers["x-request-id"]??randomUUID()),correlationId:String(req.headers["x-correlation-id"]??randomUUID())}:null;}
function dto(r:any){return{itemId:r.id,productId:r.product_id,lotId:r.lot_id,quantity:Number(r.quantity),unit:r.unit,expiresAt:r.expires_at,expirationSource:r.expiration_source,location:r.location,lotCode:r.lot_code,addedAt:r.added_at,openedAt:r.opened_at,updatedAt:r.updated_at,version:r.version};}
async function authorizeFamily(cctx:Ctx, write:boolean):Promise<{ok:true}|{ok:false,status:number,code:string,message:string}|{ok:false,status:503,code:"FAMILY_AUTH_UNAVAILABLE",message:string}>{
 try{
  const response=await fetch(familyServiceBaseUrl+"/families/"+encodeURIComponent(cctx.familyId)+"/members",{headers:{"x-user-id":cctx.userId,"accept":"application/json"},signal:AbortSignal.timeout(2500)});
  if(!response.ok)return {ok:false,status:503,code:"FAMILY_AUTH_UNAVAILABLE",message:"Family authorization service is unavailable."};
  const payload=await response.json() as {items?:Array<{userId:string,role:string,status:string}>};
  const member=payload.items?.find((x)=>x.userId===cctx.userId);
  if(!member||member.status!=="ACTIVE")return {ok:false,status:403,code:"FORBIDDEN",message:"User is not an active member of the family."};
  if(write&&member.role==="viewer")return {ok:false,status:403,code:"FORBIDDEN",message:"Viewer role is read-only."};
  return {ok:true};
 }catch{
  return {ok:false,status:503,code:"FAMILY_AUTH_UNAVAILABLE",message:"Family authorization service is unavailable."};
}
const reqHash=(v:unknown)=>createHash("sha256").update(JSON.stringify(v)).digest("hex");
async function idem(c:PoolClient,key:string,ctx:Ctx,b:unknown){const h=reqHash(b);const q=await c.query("select * from idempotency_keys where key=$1 for update",[key]);if(q.rowCount){const r=q.rows[0];if(r.actor_user_id!==ctx.userId||r.request_hash!==h)return {conflict:true};if(r.status==="completed")return {status:r.response_status,body:r.response_body};return null;}await c.query("insert into idempotency_keys(key,actor_user_id,family_id,request_hash,status,created_at,expires_at) values($1,$2,$3,$4,'processing',now(),now()+interval '24 hours')",[key,ctx.userId,ctx.familyId,h]);return null;}
async function finish(c:PoolClient,key:string,s:number,b:unknown){await c.query("update idempotency_keys set status='completed',response_status=$2,response_body=$3 where key=$1",[key,s,JSON.stringify(b)]);}
async function event(c:PoolClient,type:string,aggregateId:string,ctx:Ctx,payload:unknown){const id=randomUUID();await c.query("insert into outbox_events(id,event_id,event_type,schema_version,aggregate_id,family_id,correlation_id,occurred_at,payload,created_at) values($1,$1,$2,1,$3,$4,$5,now(),$6,now())",[id,type,aggregateId,ctx.familyId,ctx.correlationId,JSON.stringify(payload)]);}

const server=createServer(async(req,res)=>{
 const id=String(req.headers["x-request-id"]??randomUUID());
 try{
  if(req.url==="/health/live")return send(res,200,{status:"ok",service},id);
  if(req.url==="/health/ready"){await pool.query("select 1");return send(res,200,{status:"ready",service},id);}
  const cctx=ctx(req);if(!cctx)return fail(res,401,"UNAUTHENTICATED","Missing authenticated family context.",id);
  const u=new URL(req.url??"/","http://inventory");const p=u.pathname;
  if(req.method==="GET"&&p==="/api/v1/inventory"){const q=await pool.query("select * from pantry_items where family_id=$1 order by added_at desc limit 100",[cctx.familyId]);return send(res,200,{items:q.rows.map(dto),nextCursor:null},cctx.requestId);}
  const m=p.match(/^\/api\/v1\/inventory\/([0-9a-f-]+)(?:\/(consume|waste|movements|expiration\/confirm))?$/i);
  if(req.method==="GET"&&m&&!m[2]){const q=await pool.query("select * from pantry_items where id=$1 and family_id=$2",[m[1],cctx.familyId]);return q.rowCount?send(res,200,{data:dto(q.rows[0])},cctx.requestId):fail(res,404,"NOT_FOUND","Inventory item not found.",cctx.requestId);}
  if(req.method==="GET"&&m?.[2]==="movements"){const q=await pool.query("select id,product_id,type,quantity,unit,reason,occurred_at,actor_user_id from movements where pantry_item_id=$1 and family_id=$2 order by occurred_at desc limit 100",[m[1],cctx.familyId]);return send(res,200,{items:q.rows.map(x=>({movementId:x.id,productId:x.product_id,type:x.type,quantity:Number(x.quantity),unit:x.unit,reason:x.reason,occurredAt:x.occurred_at,actorUserId:x.actor_user_id})),nextCursor:null},cctx.requestId);}
  if(req.method==="POST"&&p==="/api/v1/inventory/items"){const b=await body(req);const qty=Number(b.quantity);if(!b.productId||!b.unit||!Number.isFinite(qty)||qty<=0)return fail(res,400,"VALIDATION_ERROR","productId, unit and positive quantity are required.",cctx.requestId);const key=String(req.headers["x-idempotency-key"]??"");if(!key)return fail(res,400,"VALIDATION_ERROR","X-Idempotency-Key is required.",cctx.requestId);const c=await pool.connect();try{await c.query("begin");const old=await idem(c,key,cctx,b);if(old?.conflict){await c.query("rollback");return fail(res,409,"CONFLICT","Idempotency key conflict.",cctx.requestId);}if(old?.body){await c.query("commit");return send(res,old.status,old.body,cctx.requestId);}const id=randomUUID();const q=await c.query("insert into pantry_items(id,family_id,product_id,quantity,unit,location,expires_at,expiration_source,lot_code,added_at,created_at,updated_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,now(),now(),now()) returning *",[id,cctx.familyId,String(b.productId),qty,String(b.unit),b.location??null,b.expiresAt?new Date(String(b.expiresAt)):null,b.expiresAt?"declared":null,b.lotCode??null]);await c.query("insert into movements(id,family_id,pantry_item_id,product_id,type,quantity,unit,reason,actor_user_id,occurred_at,created_at) values($1,$2,$3,$4,'add',$5,$6,'added',$7,now(),now())",[randomUUID(),cctx.familyId,id,b.productId,qty,b.unit,cctx.userId]);await event(c,"PantryItemAdjusted",id,cctx,{action:"add",item:dto(q.rows[0])});const out={data:dto(q.rows[0]),version:q.rows[0].version};await finish(c,key,201,out);await c.query("commit");return send(res,201,out,cctx.requestId);}catch(e){await c.query("rollback");throw e}finally{c.release();}}
  if(req.method==="PATCH"&&m&&!m[2]){const b=await body(req),key=String(req.headers["x-idempotency-key"]??"");if(!key)return fail(res,400,"VALIDATION_ERROR","X-Idempotency-Key is required.",cctx.requestId);const ifMatchHeader=String(req.headers["if-match"]??"");if(!/^[0-9]+$/.test(ifMatchHeader)||Number(ifMatchHeader)<1)return fail(res,428,"PRECONDITION_REQUIRED","If-Match is required.",cctx.requestId);const c=await pool.connect();try{await c.query("begin");const old=await idem(c,key,cctx,b);if(old?.conflict){await c.query("rollback");return fail(res,409,"CONFLICT","Idempotency key conflict.",cctx.requestId);}if(old?.body){await c.query("commit");return send(res,old.status,old.body,cctx.requestId);}const q=await c.query("select * from pantry_items where id=$1 and family_id=$2 for update",[m[1],cctx.familyId]);if(!q.rowCount){await c.query("rollback");return fail(res,404,"NOT_FOUND","Inventory item not found.",cctx.requestId);}const expected=Number(ifMatchHeader);if(expected!==q.rows[0].version){await c.query("rollback");return fail(res,412,"PRECONDITION_FAILED","Item version changed.",cctx.requestId);}const x=await c.query("update pantry_items set quantity=coalesce($3,quantity),location=coalesce($4,location),expires_at=case when $5 then $6 else expires_at end,expiration_source=case when $5 then 'declared' else expiration_source end,lot_code=coalesce($7,lot_code),updated_at=now(),version=version+1 where id=$1 and family_id=$2 returning *",[m[1],cctx.familyId,b.quantity??null,b.location??null,Object.hasOwn(b,"expiresAt"),b.expiresAt?new Date(String(b.expiresAt)):null,b.lotCode??null]);if(Number(x.rows[0].quantity)<=0){await c.query("rollback");return fail(res,422,"BUSINESS_RULE_VIOLATION","Quantity must remain positive.",cctx.requestId);}await event(c,"PantryItemAdjusted",m[1],cctx,{action:"adjust",item:dto(x.rows[0])});const out={data:dto(x.rows[0]),version:x.rows[0].version};await finish(c,key,200,out);await c.query("commit");return send(res,200,out,cctx.requestId);}catch(e){await c.query("rollback");throw e}finally{c.release();}}
  if(req.method==="POST"&&m?.[2]&&["consume","waste"].includes(m[2])){const b=await body(req),qty=Number(b.quantity),key=String(req.headers["x-idempotency-key"]??""),ifm=String(req.headers["if-match"]??"");if(!key||!Number.isFinite(qty)||qty<=0)return fail(res,400,"VALIDATION_ERROR","Positive quantity and X-Idempotency-Key are required.",cctx.requestId);if(!/^[0-9]+$/.test(ifm)||Number(ifm)<1)return fail(res,428,"PRECONDITION_REQUIRED","If-Match is required.",cctx.requestId);const c=await pool.connect();try{await c.query("begin");const old=await idem(c,key,cctx,b);if(old?.conflict){await c.query("rollback");return fail(res,409,"CONFLICT","Idempotency key conflict.",cctx.requestId);}if(old?.body){await c.query("commit");return send(res,old.status,old.body,cctx.requestId);}const q=await c.query("select * from pantry_items where id=$1 and family_id=$2 for update",[m[1],cctx.familyId]);if(!q.rowCount){await c.query("rollback");return fail(res,404,"NOT_FOUND","Inventory item not found.",cctx.requestId);}const r=q.rows[0],expected=Number(ifm);if(Number(r.version)!==expected){await c.query("rollback");return fail(res,412,"PRECONDITION_FAILED","Item version changed.",cctx.requestId);}const remaining=Number(r.quantity)-qty;if(remaining<0){await c.query("rollback");return fail(res,422,"BUSINESS_RULE_VIOLATION","Quantity exceeds available inventory.",cctx.requestId);}const removed=remaining===0;await c.query("insert into movements(id,family_id,pantry_item_id,product_id,type,quantity,unit,reason,actor_user_id,occurred_at,created_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,now(),now())",[randomUUID(),cctx.familyId,removed?null:r.id,r.product_id,m[2]==="consume"?"consume":"waste",qty,r.unit,b.reason??null,cctx.userId]);if(removed)await c.query("delete from pantry_items where id=$1 and family_id=$2",[r.id,cctx.familyId]);else await c.query("update pantry_items set quantity=$3,updated_at=now(),version=version+1 where id=$1 and family_id=$2",[r.id,cctx.familyId,remaining]);await event(c,"PantryItemAdjusted",r.id,cctx,{action:m[2],productId:r.product_id,quantity:qty,remainingQuantity:remaining,removed});const out={data:{itemId:r.id,[m[2]==="consume"?"consumedQuantity":"wastedQuantity"]:qty,remainingQuantity:remaining,removed},version:r.version+1};await finish(c,key,200,out);await c.query("commit");return send(res,200,out,cctx.requestId);}catch(e){await c.query("rollback");throw e}finally{c.release();}}
  if(req.method==="POST"&&m?.[2]==="expiration/confirm"){const b=await body(req),key=String(req.headers["x-idempotency-key"]??"");if(!key)return fail(res,400,"VALIDATION_ERROR","X-Idempotency-Key is required.",cctx.requestId);const source=String(b.source??"");if(!b.expiresAt||!["declared","estimated"].includes(source))return fail(res,400,"VALIDATION_ERROR","expiresAt and source are required.",cctx.requestId);const c=await pool.connect();try{await c.query("begin");const old=await idem(c,key,cctx,b);if(old?.conflict){await c.query("rollback");return fail(res,409,"CONFLICT","Idempotency key conflict.",cctx.requestId);}if(old?.body){await c.query("commit");return send(res,old.status,old.body,cctx.requestId);}const expiresAt=new Date(String(b.expiresAt));if(Number.isNaN(expiresAt.getTime())){await c.query("rollback");return fail(res,400,"VALIDATION_ERROR","expiresAt is invalid.",cctx.requestId);}const q=await c.query("update pantry_items set expires_at=$3,expiration_source=$4,updated_at=now(),version=version+1 where id=$1 and family_id=$2 returning *",[m[1],cctx.familyId,expiresAt,source]);if(!q.rowCount){await c.query("rollback");return fail(res,404,"NOT_FOUND","Inventory item not found.",cctx.requestId);}const out={data:dto(q.rows[0]),version:q.rows[0].version};await event(c,"PantryItemAdjusted",m[1],cctx,{action:"expiration_confirmed",item:out.data});await finish(c,key,200,out);await c.query("commit");return send(res,200,out,cctx.requestId);}catch(e){await c.query("rollback");throw e}finally{c.release();}}
  return fail(res,404,"NOT_FOUND","Route not found.",cctx.requestId);
 }catch(e){console.error(JSON.stringify({service,event:"request.failed",error:String(e)}));return fail(res,500,"INTERNAL_ERROR","Unexpected internal error.",id);}
});
server.listen(port,"0.0.0.0",()=>console.log(JSON.stringify({service,port})));
