import { createServer, type ServerResponse } from "node:http";
import { randomUUID } from "node:crypto";
const port = Number(process.env.PORT ?? 3022), service = process.env.SERVICE_NAME ?? "nutrition";
let requests = 0, errors = 0, totalMs = 0, inFlight = 0;
type LogFields = Record<string, unknown>;
const serializeError = (error: unknown): LogFields => error instanceof Error ? { name: error.name, message: error.message, stack: error.stack } : { value: String(error) };
const log = (level: string, event: string, fields: LogFields = {}, error?: unknown) => console.log(JSON.stringify({ ts: new Date().toISOString(), level, service, event, ...fields, ...(error !== undefined ? { error: serializeError(error) } : {}) }));
const send = (res: ServerResponse, status: number, body: unknown, requestId: string) => { res.statusCode = status; res.setHeader("content-type", "application/json"); res.setHeader("x-request-id", requestId); res.end(JSON.stringify(body)); };
createServer((req, res) => { const started = process.hrtime.bigint(), requestId = String(req.headers["x-request-id"] ?? randomUUID()), traceparent = String(req.headers.traceparent ?? ""); inFlight++; res.setHeader("x-request-id", requestId); if (traceparent) res.setHeader("traceparent", traceparent); try { if (req.url === "/metrics") { res.statusCode = 200; res.setHeader("content-type", "text/plain; version=0.0.4"); res.end(`# TYPE http_requests_total counter\nhttp_requests_total ${requests}\n# TYPE http_errors_total counter\nhttp_errors_total ${errors}\n# TYPE http_requests_in_flight gauge\nhttp_requests_in_flight ${inFlight}\n# TYPE http_request_duration_ms_sum counter\nhttp_request_duration_ms_sum ${totalMs}\n`); return; } if (req.url === "/health/live") { send(res, 200, { status: "ok", service }, requestId); return; } if (req.url === "/health/ready") { send(res, 200, { status: "ok", service, ready: true }, requestId); return; } send(res, 404, { error: "route_not_implemented", service }, requestId); } catch (error) { errors++; send(res, 500, { error: "internal_error", requestId }, requestId); log("error", "request.failed", { requestId }, error); } finally { inFlight--; requests++; const durationMs = Number(process.hrtime.bigint() - started) / 1e6; totalMs += durationMs; log("info", "http.request", { requestId, traceparent: traceparent || undefined, method: req.method, path: req.url, status: res.statusCode, durationMs: Math.round(durationMs * 10) / 10 }); } }).listen(port, "0.0.0.0", () => log("info", "service.started", { port }));
