import express from "express";import {Pool} from "pg";
const app=express();app.use(express.json({limit:"2mb"}));const pool=new Pool({connectionString:process.env.DATABASE_URL});const s="stores_domain";const port=Number(process.env.PORT??3403);
app.get("/health/live",(_,r)=>r.json({status:"ok",service:"service-stores"}));app.get("/health/ready",async(_,r)=>{try{await pool.query("select 1");r.json({status:"ok"})}catch{r.status(503).json({status:"not_ready"})}});
app.get("/api/v1/stores",async(req,res)=>{const q=await pool.query(`select * from ${s}.stores where family_id=$1 and status='ACTIVE' order by name`,[String(req.query.familyId??"")]);res.json({data:q.rows})});
app.post("/api/v1/stores",async(req,res)=>{const b=req.body??{};const q=await pool.query(`insert into ${s}.stores(family_id,name,chain,address,latitude,longitude) values($1,$2,$3,$4,$5,$6) returning *`,[b.familyId,b.name,b.chain??null,b.address??null,b.latitude??null,b.longitude??null]);res.status(201).json({data:q.rows[0]})});
app.get("/api/v1/stores/price-history",async(req,res)=>{const q=await pool.query(`select * from ${s}.store_prices where product_id=$1 and ($2='' or store_id=$2::uuid) order by observed_at desc limit 500`,[String(req.query.productId??""),String(req.query.storeId??"")]);res.json({data:q.rows})});
app.get("/api/v1/stores/:storeId/products",async(req,res)=>{const q=await pool.query(`select p.*,pr.* from ${s}.store_prices pr join public.products p on p.id=pr.product_id where pr.store_id=$1 order by pr.observed_at desc limit 500`,[req.params.storeId]);res.json({data:q.rows})});
app.post("/api/v1/stores/:storeId/prices",async(req,res)=>{const b=req.body??{};const q=await pool.query(`insert into ${s}.store_prices(store_id,product_id,price,currency,unit_price,is_offer,offer_ends_at,source,observed_at) values($1,$2,$3,$4,$5,$6,$7,$8,coalesce($9,now())) returning *`,[req.params.storeId,b.productId,b.price,b.currency??"EUR",b.unitPrice??null,b.isOffer??false,b.offerEndsAt??null,b.source??"MANUAL",b.observedAt??null]);res.status(201).json({data:q.rows[0]})});
app.listen(port,"0.0.0.0",()=>console.log(JSON.stringify({service:"service-stores",port})));
