import express from "express";import {Pool} from "pg";import crypto from "node:crypto";
const app=express();app.use(express.json({limit:"1mb"}));const port=Number(process.env.PORT??3403);const pool=new Pool({connectionString:process.env.DATABASE_URL});
const fail=(res:express.Response,s:number,c:string,m:string)=>res.status(s).json({error:{code:c,message:m,details:[],requestId:crypto.randomUUID()}});
async function init(){await pool.query(`create schema if not exists stores_domain`);await pool.query(`create table if not exists stores_domain.stores(id uuid primary key,name varchar(200) not null,chain varchar(200),address varchar(500),version integer not null default 1,created_at timestamptz not null default now())`);await pool.query(`create table if not exists stores_domain.prices(id uuid primary key,store_id uuid not null references stores_domain.stores(id) on delete cascade,product_id uuid not null,amount_minor bigint not null check(amount_minor>=0),currency char(3) not null,observed_at timestamptz not null,source varchar(64) not null,version integer not null default 1)`);await pool.query(`create table if not exists stores_domain.offers(id uuid primary key,store_id uuid not null references stores_domain.stores(id) on delete cascade,product_id uuid not null,type varchar(32) not null,value numeric not null,valid_from timestamptz not null,valid_to timestamptz not null,version integer not null default 1)`);}
app.get("/health/live",(_q,r)=>r.json({status:"ok",service:"service-stores"}));app.get("/health/ready",async(_q,r)=>{try{await pool.query("select 1");r.json({status:"ready"})}catch{r.status(503).json({status:"not_ready"})}});
app.get("/api/v1/stores",async(req,res)=>{const q=await pool.query("select * from stores_domain.stores where ($1='' or lower(name) like lower('%'||$1||'%')) order by name limit $2",[String(req.query.q??""),Math.min(Math.max(Number(req.query.limit??50),1),100)]);res.json({items:q.rows.map(x=>({storeId:x.id,name:x.name,chain:x.chain,address:x.address})),nextCursor:null})});
app.post("/api/v1/stores",async(req,res)=>{const b=req.body??{};if(!String(b.name??"").trim())return fail(res,400,"VALIDATION_ERROR","name is required.");const q=await pool.query("insert into stores_domain.stores(id,name,chain,address) values($1,$2,$3,$4) returning *",[crypto.randomUUID(),b.name,b.chain??null,b.address??null]);const x=q.rows[0];res.status(201).json({data:{storeId:x.id,name:x.name,chain:x.chain,address:x.address},version:x.version})});
app.get("/api/v1/stores/:storeId/prices",async(req,res)=>{const q=await pool.query("select * from stores_domain.prices where store_id=$1 and ($2='' or product_id=$2::uuid) order by observed_at desc limit $3",[req.params.storeId,String(req.query.productId??""),Math.min(Math.max(Number(req.query.limit??50),1),100)]);res.json({items:q.rows.map(x=>({priceId:x.id,productId:x.product_id,storeId:x.store_id,amountMinor:Number(x.amount_minor),currency:x.currency,observedAt:x.observed_at})),nextCursor:null})});
app.post("/api/v1/stores/:storeId/prices",async(req,res)=>{const b=req.body??{};if(!b.productId||!Number.isInteger(Number(b.amountMinor))||Number(b.amountMinor)<0||!b.currency||!b.observedAt||!b.source)return fail(res,400,"VALIDATION_ERROR","productId, amountMinor, currency, observedAt and source are required.");const q=await pool.query("insert into stores_domain.prices(id,store_id,product_id,amount_minor,currency,observed_at,source) values($1,$2,$3,$4,$5,$6,$7) returning *",[crypto.randomUUID(),req.params.storeId,b.productId,b.amountMinor,b.currency,b.observedAt,b.source]);const x=q.rows[0];res.status(201).json({data:{priceId:x.id,productId:x.product_id,storeId:x.store_id,amountMinor:Number(x.amount_minor),currency:x.currency,observedAt:x.observed_at},version:x.version})});
app.get("/api/v1/stores/:storeId/offers",async(req,res)=>{const q=await pool.query("select * from stores_domain.offers where store_id=$1 and ($2=false or valid_to>=now()) and ($3='' or product_id=$3::uuid) order by valid_to",[req.params.storeId,req.query.active==="true",String(req.query.productId??"")]);res.json({items:q.rows.map(x=>({offerId:x.id,productId:x.product_id,storeId:x.store_id,type:x.type,value:Number(x.value),validFrom:x.valid_from,validTo:x.valid_to})),nextCursor:null})});
app.post("/api/v1/stores/:storeId/offers",async(req,res)=>{const b=req.body??{};if(!b.productId||!b.type||!Number.isFinite(Number(b.value))||!b.validFrom||!b.validTo)return fail(res,400,"VALIDATION_ERROR","productId, type, value, validFrom and validTo are required.");const q=await pool.query("insert into stores_domain.offers(id,store_id,product_id,type,value,valid_from,valid_to) values($1,$2,$3,$4,$5,$6,$7) returning *",[crypto.randomUUID(),req.params.storeId,b.productId,b.type,b.value,b.validFrom,b.validTo]);const x=q.rows[0];res.status(201).json({data:{offerId:x.id,productId:x.product_id,storeId:x.store_id,type:x.type,value:Number(x.value),validFrom:x.valid_from,validTo:x.valid_to},version:x.version})});
app.use((_q,r)=>fail(r,404,"NOT_FOUND","Route not found."));init().then(()=>app.listen(port,"0.0.0.0",()=>console.log(JSON.stringify({service:"service-stores",port}))).catch(e=>{console.error(e);process.exit(1)});
