import express from "express"; import {Pool} from "pg"; import crypto from "node:crypto";
const app=express();app.use(express.json({limit:"2mb"}));const port=Number(process.env.PORT??3401);const pool=new Pool({connectionString:process.env.DATABASE_URL});
const fail=(res:express.Response,s:number,c:string,m:string)=>res.status(s).json({error:{code:c,message:m,details:[],requestId:crypto.randomUUID()}});
async function init(){await pool.query(`create schema if not exists recipes_domain`);await pool.query(`create table if not exists recipes_domain.recipes(id uuid primary key,family_id uuid null,owner_user_id uuid null,title varchar(300) not null,servings integer not null,ingredients jsonb not null default '[]',steps jsonb not null default '[]',version integer not null default 1,created_at timestamptz not null default now(),updated_at timestamptz not null default now())`);}
app.get("/health/live",(_q,r)=>r.json({status:"ok",service:"service-recipes"}));app.get("/health/ready",async(_q,r)=>{try{await pool.query("select 1");r.json({status:"ready"})}catch{r.status(503).json({status:"not_ready"})}});
const dto=(x:any)=>({recipeId:x.id,title:x.title,servings:x.servings,ingredients:x.ingredients,steps:x.steps,version:x.version});
app.get("/api/v1/recipes",async(req,res)=>{const f=String(req.query.familyId??req.header("x-family-id")??"");const l=Math.min(Math.max(Number(req.query.limit??50),1),100);const q=await pool.query(`select * from recipes_domain.recipes where ($1='' or family_id=$1::uuid) order by created_at desc limit $2`,[f,l]);res.json({items:q.rows.map(dto),nextCursor:null})});
app.post("/api/v1/recipes",async(req,res)=>{const b=req.body??{};if(!String(b.title??"").trim()||!Number.isInteger(b.servings)||b.servings<1)return fail(res,400,"VALIDATION_ERROR","title and positive servings are required.");const id=crypto.randomUUID();const q=await pool.query(`insert into recipes_domain.recipes(id,family_id,owner_user_id,title,servings,ingredients,steps) values($1,$2,$3,$4,$5,$6,$7) returning *`,[id,b.familyId??req.header("x-family-id")??null,req.header("x-user-id")??null,b.title,b.servings,JSON.stringify(b.ingredients??[]),JSON.stringify(b.steps??[])]);res.status(201).json({data:dto(q.rows[0]),version:q.rows[0].version})});
app.get("/api/v1/recipes/suggestions",async(req,res)=>{const f=String(req.query.familyId??req.header("x-family-id")??"");const q=await pool.query(`select * from recipes_domain.recipes where ($1='' or family_id=$1::uuid) order by updated_at desc limit $2`,[f,Math.min(Math.max(Number(req.query.limit??20),1),100)]);res.json({items:q.rows.map(x=>({recipeId:x.id,score:1,missingIngredients:[]}))})});
app.get("/api/v1/recipes/:recipeId",async(req,res)=>{const q=await pool.query("select * from recipes_domain.recipes where id=$1",[req.params.recipeId]);if(!q.rowCount)return fail(res,404,"NOT_FOUND","Recipe not found.");res.json({data:dto(q.rows[0])})});
app.patch("/api/v1/recipes/:recipeId",async(req,res)=>{const b=req.body??{};const q=await pool.query(`update recipes_domain.recipes set title=coalesce($2,title),servings=coalesce($3,servings),ingredients=coalesce($4,ingredients),steps=coalesce($5,steps),version=version+1,updated_at=now() where id=$1 returning *`,[req.params.recipeId,b.title,b.servings,b.ingredients?JSON.stringify(b.ingredients):null,b.steps?JSON.stringify(b.steps):null]);if(!q.rowCount)return fail(res,404,"NOT_FOUND","Recipe not found.");res.json({data:dto(q.rows[0]),version:q.rows[0].version})});
app.delete("/api/v1/recipes/:recipeId",async(req,res)=>{const q=await pool.query("delete from recipes_domain.recipes where id=$1 returning id",[req.params.recipeId]);if(!q.rowCount)return fail(res,404,"NOT_FOUND","Recipe not found.");res.status(204).end()});
app.use((_q,r)=>fail(r,404,"NOT_FOUND","Route not found."));init().then(()=>app.listen(port,"0.0.0.0",()=>console.log(JSON.stringify({service:"service-recipes",port}))).catch(e=>{console.error(e);process.exit(1)});
